### ISSUE TITLE
Any plans to update to 1.4?

### ISSUE THREAD

**Issue by SPAHI4** [just-boris/polymer-ymaps#3]

**Comment by just-boris** [comment]
Hello!

What dependency did you mean? I don't see anything that has 1.4 recent release.

:warning: Note that it repository for [Polymer component](https://www.polymer-project.org/1.0/), which latest version is 1.0.

**Comment by SPAHI4** [comment]
@just-boris I mean Polymer 
https://github.com/Polymer/polymer/releases

**Comment by just-boris** [comment]
@SPAHI4 thanks for pointing this out.

Actually, I used to work with Polymer few years ago (when it was version 0.5). So now I am not aware of latest changes and can't update this very fast.

Also, any help (at least link to migration guides or even real fixes) will be appreciated.

**Comment by qertis** [comment]
I did it

**Comment by just-boris** [comment]
Merged.
We have stepped over couple releases and now it works well with version 1.8.

Whenever 2.0 will be released, I also would be happy to merge respective PR as well.
